version: '3.7'
services:
  traefik:
    restart: unless-stopped
    image: traefik:v3.0
    ports:
      - '443:443'
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml

  chatmastr:
    image: ghcr.io/ryuumax/chatmastr:master
    pull_policy: always
    ports:
      - '80:8501'
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatmastr.rule=Host(`a100.rc.th-b.com`) && Pathprefix(`/chatmastr`)
    volumes:
      - /home/user/KnowledgeBase:/app/KnowledgeBase
    environment:
      - OPENAI_API_BASE=http://host.docker.internal:8082/v1
      - STREAMLIT_CONFIG_SERVER_BASEURLPATH=/chatmastr
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  traefik:
    external: true