version: '3.7'
services:
  traefik:
    restart: unless-stopped
    image: traefik:v3.0
    ports:
      - '443:443'
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/user/chatmastr/traefik.yml:/traefik.yml
      - /home/user/chatmastr/traefik_dynconf.yml:/app/traefik_dynconf.yml
      - /home/user/letsencrypt:/app/letsencrypt:ro

  chatmastr:
    image: ghcr.io/ryuumax/chatmastr:master
    pull_policy: always
    ports:
      - '80:8501'
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatmastr.rule=Host(`a100.rc.th-b.com`) && PathPrefix(`/chatmastr`)
      - traefik.http.routers.chatmastr.tls=true
    volumes:
      - /home/user/KnowledgeBase:/app/KnowledgeBase
    environment:
      - OPENAI_API_BASE=http://host.docker.internal:8082/v1
      - STREAMLIT_SERVER_BASE_URL_PATH=/chatmastr
    extra_hosts:
      - "host.docker.internal:host-gateway"

  promptcomposer:
    image: ghcr.io/tuuby/ai-prompt-composer:master
    pull_policy: always
    environment:
      - OPEN_AI_API_KEY=EMPTY
      - OPEN_AI_API_BASE=http://host.docker.internal:8082/v1
      - WEB_BASE_URL=/promptcomposer
      - OPEN_AI_API_MAX_TOKENS=1024
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.promptcomposer.rule=Host(`a100.rc.th-b.com`) && PathPrefix(`/promptcomposer`)
      - traefik.http.routers.promptcomposer.tls=true
    ports:
      - '1234:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik:
    external: true