log:
  level: INFO

entryPoints:
  web:
    address: ':443'
api:
  dashboard: true
  insecure: true

providers:
  docker:
    watch: true
    network: traefik
    exposedByDefault: false
  file:
    filename: /app/traefik_dynconf.yml